### ISSUE TITLE
Rad Importing other modules methods as the Application Method

### ISSUE THREAD

**Issue by samircury** [garu/App-Rad#1]
Hi,

I was trying to use Rad with an already written app, and it seem that it's showing other modules methods as commands, I already heard a talk about this and a way to prevent, but I'm not sure. 

Here is a part of the output :

./stale_data.pl 
Usage: ./stale_data.pl command [arguments]

Available Commands:
    DateCalc  
    DateManipVersion  
    Date_Cmp  
    Date_ConvTZ  
    Date_DayOfWeek          

And many more.

Is there a way to prevent this leak?
Thanks,
Samir

**Comment by garu** [comment]
Sure, just add "use namespace::autoclean;" to your app :-)

Also, remember you can always register commands manually if you want to fine-tune what you want the client to "see".

Let me know if namespace::autoclean doesn't work, or if you have any other issues!

**Comment by samircury** [comment]
It totally solved, thanks!
