### ISSUE TITLE
--option value or -o value

### ISSUE THREAD

**Issue by samircury** [garu/App-Rad#2]
Hi,

Is it a straightforward way to make this happen? I didn't found this on the docs, what I could get from there is just :

--option=value 

or
-o => this one will just be a flag --o=value or -o=value doesn't work also.

If is not supported I would put this on the wishlist =)

Cheers,
Samir

**Comment by alnewkirk** [comment]
See App-Rad, Advanced GetOpt Usage -  http://goo.gl/bNeoe

**Comment by samircury** [comment]
nice, the example in Rad's POD is simple, but getopt::Long is not that simple, reading both manuals I managed to do it, many thanks!
